# Supporting resources. You do not edit this file in Challenge 05 — it exists so
# that `terraform validate` has every reference in ecs_service.tf resolved.

terraform {
  required_version = ">= 1.11"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 6.0"
    }
  }
}

provider "aws" {
  region = "us-east-1"

  # No credentials are used. Nothing in this lab is ever applied.
  skip_credentials_validation = true
  skip_requesting_account_id  = true
  skip_metadata_api_check     = true
}

resource "aws_security_group" "phr_api" {
  name        = "phr-api-${var.owner_initials}"
  description = "PHR API tasks"
  vpc_id      = var.vpc_id

  ingress {
    description = "ALB to task"
    from_port   = 8080
    to_port     = 8080
    protocol    = "tcp"
    cidr_blocks = ["10.0.0.0/8"]
  }

  egress {
    description = "Task to internet"
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }
}

resource "aws_ecs_task_definition" "phr_api" {
  family                   = "phr-api"
  requires_compatibilities = ["FARGATE"]
  network_mode             = "awsvpc"
  cpu                      = "256"
  memory                   = "512"
  execution_role_arn       = aws_iam_role.task_execution.arn

  container_definitions = jsonencode([
    {
      name      = "phr-api"
      image     = "ghcr.io/example/phr-api:1.2.4"
      essential = true
      portMappings = [
        {
          containerPort = 8080
          protocol      = "tcp"
        }
      ]
    }
  ])
}

resource "aws_iam_role" "task_execution" {
  name = "phr-api-task-execution-${var.owner_initials}"

  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Effect    = "Allow"
        Principal = { Service = "ecs-tasks.amazonaws.com" }
        Action    = "sts:AssumeRole"
      }
    ]
  })
}

# The role ECS assumes to run a blue/green cutover on your behalf. Challenge 05
# references this from the service.
resource "aws_iam_role" "ecs_bluegreen" {
  name = "phr-api-bluegreen-${var.owner_initials}"

  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Effect    = "Allow"
        Principal = { Service = "ecs.amazonaws.com" }
        Action    = "sts:AssumeRole"
      }
    ]
  })
}
